### ISSUE TITLE
Slapdash spelling in comment

### ISSUE THREAD

**Issue by timothyheron** [csuhj/cattracker2000#1]
In pi_surveillance.py, line 126 'break from the lop'.

Non-standard English.  Do you know a proof-reader?

**Comment by csuhj** [comment]
Good spot :)

This code was (ahem) copied from the blog article in the README.  I'll tidy up

**Comment by csuhj** [comment]
Fixed in commit https://github.com/csuhj/cattracker2000/commit/ac5a422d1efe14708276685286ca1d3c9c3625a2#diff-ce935d9931e12f36eabc05300f1ba8ac
